Repository ouzi-dev/prow-installer, pull requests merged in 2020-04, with the labels that each got.

#22 fix: update npm deps to latest version
  Makefile
  package-lock.json
  package.json
Labels: approved, lgtm, size/XXL

#23 feat: add gke preemtible tolerations
  packages/04-certmanager/01-helm/values.yaml
  packages/05-oauthproxy/00-manifests/04-deployment.yaml
  packages/06-externaldns/01-helm/values.yaml
  packages/07-nginxingress/01-helm/values.yaml
  packages/08-prow/values.yaml
  packages/10-credstashoperator/00-manifests/03.deployment.yaml
  packages/11-gkepreemptiblekiller/00-manifests/04-deployment.yaml
  packages/12-gkenodeterminationhandler/00-manifests/02-k8s.yaml
Labels: approved, lgtm, size/M

#24 fix: upgrade prow to v0.8.0 helm chart
  packages/08-prow/values.yaml
Labels: approved, lgtm, size/XS

#25 feat: update all components to latest versions
  Makefile
  packages/04-certmanager/values.yaml
  packages/05-oauthproxy/00-manifests/04-deployment.yaml
  packages/05-oauthproxy/values.yaml
  packages/06-externaldns/values.yaml
  packages/07-nginxingress/values.yaml
Labels: approved, lgtm, size/S
